apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ping-demo
  name: ping-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-demo
  template:
    metadata:
      labels:
        app: ping-demo
    spec:
      containers:
      - image: us-docker.pkg.dev/gke-demos-345619/gke-demos/ping-demo@sha256:8e6715a38fe2c790b9829c57e0a16e8d997d01245013e9dffa31957d7e728b1d
        name: ping-demo
        resources:
          requests:
            cpu: 50m
            ephemeral-storage: 1Gi
            memory: 52Mi
          limits:
            cpu: 50m
            ephemeral-storage: 1Gi
            memory: 52Mi